### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by J08nY** [Ledger-Donjon/rainbow#58]
It would be really helpful if this package would be available on [pypi.org](https://pypi.org).

Currently, one of my projects [pyecsca-codegen](https://github.com/J08nY/pyecsca-codegen) depends on it and its new version cannot be pushed to pypi.org because of this dependency.

I could help with the release. The package name would need to be adjusted for it (perhaps "ledger-rainbow" or "donjon-rainbow") as there is already a "rainbow" package on pypi. But that should be it. See the steps [here](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives).

We do have a tutorial that takes place in two weeks that uses the pyecsca-codegen package, so having it out by then would help quite a bit in being able to let users install the pacakges from pypi. I understand asking for work in OSS and pushing for deadlines is wild, so please take it as a kind ask, I appreciate that you are keeping the tool alive and the work you did :+1:.

**Comment by yhql** [comment]
Thank you for the detailed issue, we've had this in mind for a while and I'll have some time to get to it before your deadline

**Comment by J08nY** [comment]
Niice! Thanks. I will test the install!

**Comment by J08nY** [comment]
Install works!
